# Copyright 2020 NVIDIA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for network-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfd:
  enabled: true

node-feature-discovery:
  worker:
    options:
      sources:
        pci:
          deviceClassWhitelist:
            - "03"
            - "0302"
            - "02"
            - "0200"
operator:
  repository: harbor.mellanox.com/cloud-orchestration
  image: network-operator
  tag: latest

deployCR: true
ofedDriver:
  deploy: false

nvPeerDriver:
  deploy: false

devicePlugin:
  deploy: false

secondaryNetwork:
  deploy: true
  cniPlugins:
    deploy: true
    image: containernetworking-plugins
    repository: mellanox
    version: v0.8.7
  multus:
    deploy: true
    image: multus
    repository: nfvpe
    version: v3.6
    config: ""
  ipamPlugin:
    deploy: true
    image: whereabouts
    repository: dougbtv
    version: v0.3
